[package]
name = "cyberschool_template"
version = "0.1.2"
entrypoint = "src/lib.typ"
authors = ["ErrorTeaPot contact.233s7@simplelogin.com"]
license = "MIT"
description = "This is a template originaly made for the Cyberschool of Rennes, a Cybersecurity school"
#homepage = ""
repository = "https://github.com/ErrorTeaPot/Cyberschool_template"
#keywords = []
#categories = []
#disciplines = []
compiler = "0.12.0"
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
